# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: gnuton/vitasdk-docker:latest

steps:
- script: sudo apt-get install -qq -y pkg-config
  displayName: 'Install extra dependencies'

- script: sudo apt-get install -qq -y libc6-dev-i386
  displayName: 'Install 32 bit libraries'
  
- script: sudo apt-get install -qq -y zip
  displayName: 'Install zip'
  
- script: |
    git clone https://github.com/Rinnegatamante/math-neon
    cd math-neon
    make
    sudo -E make install
  displayName: 'Build libmathneon'

- script: |
    git clone https://github.com/Rinnegatamante/vitaGL
    cd vitaGL
    make HAVE_SBRK=1 NO_DEBUG=1
    sudo -E make HAVE_SBRK=1 NO_DEBUG=1 install
  displayName: 'Build vitaGL'

- script: |
    git clone https://github.com/Rinnegatamante/imgui-vita
    cd imgui-vita
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build dear ImGui'

- script: |
    mkdir daedbuild
    cd daedbuild
    cmake -DVITA_RELEASE=1 ../Source -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
    make -j$(nproc)
    cd ../Data
    zip -r DaedalusX64.zip DaedalusX64
  displayName: 'Build Daedalus X64'
    
- task: GitHubRelease@0
  inputs:
    gitHubConnection: release
    repositoryName: Rinnegatamante/DaedalusX64-vitaGL
    tagSource: manual
    tag: Nightly
    action: edit
    assets: |
      daedbuild/DaedalusX64.vpk
      Data/DaedalusX64.zip
  displayName: 'Deploy artifacts'
