# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: gnuton/vitasdk-docker:latest

steps:
- script: sudo apt-get install -qq -y pkg-config
  displayName: 'Install extra dependencies'

- script: sudo apt-get install -qq -y libc6-dev-i386
  displayName: 'Install 32 bit libraries'
  
- script: sudo apt-get install -qq -y zip
  displayName: 'Install zip'
  
- script: |
    git clone https://github.com/Rinnegatamante/math-neon
    cd math-neon
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build libmathneon'

- script: |
    git clone https://github.com/Rinnegatamante/vitaShaRK
    cd vitaShaRK
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build vitaShaRK'

- script: |
    git clone https://github.com/Rinnegatamante/vitaGL
    cd vitaGL
    sed -i "s/float fog_dist = coords.z \/ coords.w;/float fog_dist = coords.z;/" source/shaders/ffp_f.h
    sed -i "s/#define SHADER_CACHE_MAGIC /#define SHADER_CACHE_MAGIC 99/" source/shared.h
    make -j$(nproc) NO_DEBUG=1 HAVE_UNFLIPPED_FBOS=1 NO_TEX_COMBINER=1 SHADER_COMPILER_SPEEDHACK=1 HAVE_CUSTOM_HEAP=1
    sudo -E make NO_DEBUG=1 HAVE_UNFLIPPED_FBOS=1 NO_TEX_COMBINER=1 SHADER_COMPILER_SPEEDHACK=1 HAVE_CUSTOM_HEAP=1 install
  displayName: 'Build vitaGL'

- script: |
    git clone https://github.com/Rinnegatamante/imgui-vita
    cd imgui-vita
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build dear ImGui'

- script: |
    echo "$(cat $VITASDK/version_info.txt)"
    echo "$(git describe --abbrev=6 --dirty --always --tags)"
    mkdir daedbuild
    cd daedbuild
    cmake ../Source
    make -j$(nproc)
    cd ../Data
    zip -9 -r DaedalusX64.zip DaedalusX64
    cd ../Launcher
    make -j$(nproc)
    cp ../Source/sce_sys/icon0.png builder/assets/icon0.png
    cp ../Source/sce_sys/livearea/contents/bg.png builder/assets/bg.png
    cp ../Source/sce_sys/livearea/contents/startup.png builder/assets/startup.png
    zip -9 -r builder.zip builder
  displayName: 'Build Daedalus X64'
    
- task: GitHubRelease@1
  inputs:
    gitHubConnection: release
    repositoryName: Rinnegatamante/DaedalusX64-vitaGL
    tagSource: userSpecifiedTag
    tag: Nightly
    title: 'Nightly $(Build.BuildNumber)'
    action: edit
    assets: |
      daedbuild/DaedalusX64.vpk
      Data/DaedalusX64.zip
      daedbuild/DaedalusX64.elf
      daedbuild/DaedalusX64.self
      Launcher/builder.zip
  displayName: 'Deploy artifacts'
